### ISSUE TITLE
Add handling of csv files that violate naming conventions

### ISSUE THREAD

**Issue by JADEUSC** [reichlab/covid19-forecast-hub-validations#3]
Currently csv files that are not matched by the pat regex are just added to "other_files". These files are probably forecast files with names that violate the naming conventions. 
One such example can be found here: https://github.com/KITmetricslab/covid19-forecast-hub-de/pull/670

My solution for the german/polish hub is pretty straight forward and can be found [here](https://github.com/KITmetricslab/covid19-forecast-hub-de-validations/blob/5d8b0b3840921ad0bf028a69ae34a53f9dae14d3/main.py#L131)

**Comment by hannanabdul55** [comment]
This is done as part of https://github.com/reichlab/covid19-forecast-hub-validations/commit/f47b864df4071505d7c7e8320fc71b5eacc60729 .
