### ISSUE TITLE
check for special characters in metadata

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub-validations#33]

**Comment by nickreich** [comment]
Maybe some of this has been added already? but perhaps some edge cases are not being tested for?

Can we find an example of a file that passed but shouldn't have?

**Comment by nickreich** [comment]
https://github.com/reichlab/covid19-forecast-hub/blob/6a0d45007bb811338a6e5578c6cfbe1dd3b85f24/data-processed/FRBSF_Wilson-Econometric/metadata-FRBSF_Wilson-Econometric.txt  
This should fail because of the character `’` on line 14

**Comment by nickreich** [comment]
Likely solution: implement a check to ensure that every character is a utf-8 structure.

**Comment by vidhi-mody** [comment]
I tested https://github.com/reichlab/covid19-forecast-hub/blob/6a0d45007bb811338a6e5578c6cfbe1dd3b85f24/data-processed/FRBSF_Wilson-Econometric/metadata-FRBSF_Wilson-Econometric.txt with two different YAML validators (http://www.yamllint.com/ and https://yamlchecker.com/). It shows the file to be valid. Do we have any other example of invalid files?

**Comment by Serena-Wang** [comment]
There is another invalid example in the hub meeting agenda

**Comment by nickreich** [comment]
Here is another file that failed somewhere: https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/BPagano-RtDriven/metadata-BPagano-RtDriven.txt
