### ISSUE TITLE
check model designation 

### ISSUE THREAD

**Issue by Serena-Wang** [reichlab/covid19-forecast-hub-validations#58]
Each `team_abbr` should only has one `primary` model. A couple of options to do this:

- cache all designation info at the main branch in hub repo (issue #4) and use this cache in functions that validates metadata content

or 

- when validating a metadata in PR, query metadata info for this team from zoltpy

**Comment by Serena-Wang** [comment]
Issue #69 Issue #70 Issue #71 Issue #72 are all related to this functionality

**Comment by elray1** [comment]
Question: should this be "at most one primary model per team" or "exactly one primary model per team"?
