### ISSUE TITLE
Add unit tests for the various validations done

### ISSUE THREAD

**Issue by hannanabdul55** [reichlab/covid19-forecast-hub-validations#9]
## Description
The validations repository now has unit tests for validations. This was started when the retraction tests were added. Hence, it currently has unit tests only for the retractions. We should also add tests for the other checks that are also done. Specifically for each of the checks mentioned in [the wiki](https://github.com/reichlab/covid19-forecast-hub/wiki/Forecast-Checks).  

Add unit tests for:

- [ ] determining whether forecasts are updated.
- [ ] automerge logic.
- [ ] Metadata checks.
- [ ] Validation checks.

**Comment by nickreich** [comment]
dated. closing.
